import { Task, DiaryEntry, Sticker } from './types';

export const mockTasks: Task[] = [
  { id: '1', title: '실내 화분에 물 주기', category: '집', time: '10:00 AM', completed: false, priority: false },
  { id: '2', title: '저녁 명상 시간', category: '마음챙김', time: '15 min', completed: false, priority: true },
  { id: '3', title: '건강한 점심 준비하기', category: '셀프케어', completed: true, priority: false },
  { id: '4', title: '\'슬로우 리빙\' 20페이지 읽기', category: '자기계발', completed: false, priority: false },
];

export const mockDiaryEntries: DiaryEntry[] = [
  {
    id: 'd1',
    date: '2026-04-22',
    title: '반짝이는 기분',
    content: '오늘은 내가 피어나는 기분이었다. 공원을 산책하며 모든 것에는 각자의 성장 속도가 있다는 것을 다시금 깨달았다. 서두르지 않아도 계절은 오고 꽃은 핀다. 나 역시 나의 속도로 충분히 아름답게 나아가고 있음을 믿기로 했다.',
    mood: 'Happy',
  },
  {
    id: 'd2',
    date: '2026-04-18',
    title: '조금 지치는 날',
    content: '생각보다 일이 잘 안 풀려서 답답한 하루였다. 그래도 내일은 내일의 해가 뜰 테니까 푹 쉬어야지.',
    mood: 'Sad',
  },
  {
    id: 'd3',
    date: '2026-04-10',
    title: '오랜만의 커피 한 잔',
    content: '좋아하는 카페에 앉아 책을 읽었다. 따뜻한 라떼 한 잔의 여유가 이렇게 좋을 줄이야.',
    mood: 'Calm',
  },
  {
    id: 'd4',
    date: '2026-04-05',
    title: '화가 났던 회의',
    content: '의견 충돌이 있어서 조금 감정이 격해졌다. 감정을 다스리는 연습이 필요하다.',
    mood: 'Angry',
  },
  {
    id: 'd5',
    date: '2026-04-23',
    title: '그럭저럭 괜찮은 날',
    content: '특별한 일은 없었지만, 그래서 더 평온하고 좋았던 하루.',
    mood: 'Meh',
  }
];

export const mockStickers: Sticker[] = [
  // Decoration (Custom Image Stickers)
  {
    id: 's_heart1',
    name: '하트 1',
    description: '사랑을 담은 하트',
    category: 'Decoration',
    icon: 'Heart', // fallback
    imageUrl: '/stickers/stickers./heart1.png',
    isUnlocked: true,
  },
  {
    id: 's_heart2',
    name: '하트 2',
    description: '두 배로 사랑스러운 하트',
    category: 'Decoration',
    icon: 'Heart',
    imageUrl: '/stickers/stickers./heart2.png',
    isUnlocked: false,
    price: 30,
  },
  {
    id: 's_ribbon',
    name: '리본',
    description: '귀여운 리본 장식',
    category: 'Decoration',
    icon: 'Gift',
    imageUrl: '/stickers/stickers./ribbon.png',
    isUnlocked: true,
  },
  {
    id: 's_light1',
    name: '작은 빛',
    description: '반짝반짝 빛나요',
    category: 'Decoration',
    icon: 'Sparkles',
    imageUrl: '/stickers/stickers./light1.png',
    isUnlocked: true,
  },
  {
    id: 's_light2',
    name: '은은한 빛',
    description: '따뜻하게 감싸는 빛',
    category: 'Decoration',
    icon: 'Sparkles',
    imageUrl: '/stickers/stickers./light2.png',
    isUnlocked: false,
    price: 20,
  },
  {
    id: 's_light3',
    name: '눈부신 빛',
    description: '화려하게 빛나는 조각',
    category: 'Decoration',
    icon: 'Sparkles',
    imageUrl: '/stickers/stickers./light3.png',
    isUnlocked: false,
    price: 50,
    isRare: true,
  },
  {
    id: 's_big_star',
    name: '밤하늘의 별',
    description: '소원을 들어주는 별',
    category: 'Decoration',
    icon: 'Star',
    imageUrl: '/stickers/stickers./big star.png',
    isUnlocked: true,
  },
  {
    id: 's_big_moon',
    name: '초승달',
    description: '어둠을 밝혀주는 달',
    category: 'Decoration',
    icon: 'Moon',
    imageUrl: '/stickers/stickers./big moon.png',
    isUnlocked: false,
    price: 60,
    isRare: true,
  },
  {
    id: 's_cloudy',
    name: '몽글몽글 구름',
    description: '폭신폭신한 구름',
    category: 'Decoration',
    icon: 'Cloud',
    imageUrl: '/stickers/stickers./cloudy.png',
    isUnlocked: false,
    price: 20,
  },
  {
    id: 's_diamond',
    name: '다이아몬드',
    description: '영원히 빛나는 보석',
    category: 'Decoration',
    icon: 'Gem',
    imageUrl: '/stickers/stickers./diamond.png',
    isUnlocked: false,
    price: 150,
    isRare: true,
  },
  {
    id: 's_bubble',
    name: '영롱한 구슬',
    description: '오묘한 빛을 내는 구슬',
    category: 'Decoration',
    icon: 'Circle',
    imageUrl: '/stickers/stickers./bubble.png',
    isUnlocked: false,
    price: 40,
  },
  {
    id: 's_planet',
    name: '신비한 행성',
    description: '미지의 우주 여행',
    category: 'Decoration',
    icon: 'Globe',
    imageUrl: '/stickers/stickers./planet.png',
    isUnlocked: false,
    price: 100,
    isRare: true,
  },
  {
    id: 's_cry',
    name: '눈물방울',
    description: '작은 감정의 조각',
    category: 'Decoration',
    icon: 'Droplets',
    imageUrl: '/stickers/stickers./cry.png',
    isUnlocked: false,
    price: 10,
  },
  // Diary&Objects
  {
    id: 's_diary',
    name: '다이어리',
    description: '나만의 소중한 기록',
    category: 'Diary&Objects',
    icon: 'BookHeart',
    imageUrl: '/stickers/diary_objects/diary.png',
    isUnlocked: true,
  },
  {
    id: 's_phone',
    name: '스마트폰',
    description: '세상과 연결되는 창',
    category: 'Diary&Objects',
    icon: 'Smartphone',
    imageUrl: '/stickers/diary_objects/phone.png',
    isUnlocked: true,
  },
  {
    id: 's_player',
    name: '음악 플레이어',
    description: '나를 위로하는 멜로디',
    category: 'Diary&Objects',
    icon: 'Music',
    imageUrl: '/stickers/diary_objects/player.png',
    isUnlocked: false,
    price: 30,
  },
  {
    id: 's_key',
    name: '비밀 열쇠',
    description: '마음을 여는 열쇠',
    category: 'Diary&Objects',
    icon: 'Key',
    imageUrl: '/stickers/diary_objects/key.png',
    isUnlocked: false,
    price: 40,
  },
  {
    id: 's_lock',
    name: '자물쇠',
    description: '비밀을 간직해요',
    category: 'Diary&Objects',
    icon: 'Lock',
    imageUrl: '/stickers/diary_objects/lock.png',
    isUnlocked: false,
    price: 40,
  },
  {
    id: 's_photo',
    name: '폴라로이드',
    description: '기억하고 싶은 순간',
    category: 'Diary&Objects',
    icon: 'Camera',
    imageUrl: '/stickers/diary_objects/photo.png',
    isUnlocked: false,
    price: 50,
    isRare: true,
  },
  // Daily mood markers
  {
    id: 's_marker1',
    name: '기분 마커 1',
    description: '오늘의 감정 메모',
    category: 'Daily mood markers',
    icon: 'Pen',
    imageUrl: '/stickers/mood_markers/marker1.png',
    isUnlocked: true,
  },
  {
    id: 's_marker2',
    name: '기분 마커 2',
    description: '오늘의 기분 표시',
    category: 'Daily mood markers',
    icon: 'PenTool',
    imageUrl: '/stickers/mood_markers/marker2.png',
    isUnlocked: true,
  },
  {
    id: 's_moon_mood',
    name: '평온한 밤',
    description: '차분해지는 시간',
    category: 'Daily mood markers',
    icon: 'Moon',
    imageUrl: '/stickers/mood_markers/moon.png',
    isUnlocked: false,
    price: 20,
  },
  {
    id: 's_cloud_mood',
    name: '흐린 기분',
    description: '조금 시무룩한 날',
    category: 'Daily mood markers',
    icon: 'Cloud',
    imageUrl: '/stickers/mood_markers/cloud.png',
    isUnlocked: false,
    price: 20,
  },
  {
    id: 's_water',
    name: '물방울',
    description: '상쾌한 기분',
    category: 'Daily mood markers',
    icon: 'Droplets',
    imageUrl: '/stickers/mood_markers/water.png',
    isUnlocked: false,
    price: 30,
  },
  {
    id: 's_star_mood',
    name: '반짝이는 밤',
    description: '별처럼 빛나는 하루',
    category: 'Daily mood markers',
    icon: 'Star',
    imageUrl: '/stickers/mood_markers/star.png',
    isUnlocked: false,
    price: 40,
    isRare: true,
  },
  {
    id: 's_small_heart',
    name: '작은 두근거림',
    description: '설레는 마음',
    category: 'Daily mood markers',
    icon: 'Heart',
    imageUrl: '/stickers/mood_markers/small_heart.png',
    isUnlocked: false,
    price: 50,
    isRare: true,
  }
];
